default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: karendhiogoblog
  password: hauntmex3
  host: localhost

development:
  <<: *default
  database: terrasemflores_development

test:
  <<: *default
  database: terrasemflores_test

production:
  <<: *default
  database: terrasemflores_production
  host: db # Nome do serviço no Docker Compose
  username: karendhiogoblog
  password: hauntmex3
